export default {
  // Counter
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  
  // Checkout
  SELECT: "SELECT",
  REMOVE: "REMOVE",

  // TodoList
  GET_TASK_REQUESTING: 'GET_TASK_REQUESTING',
  GET_TASK_SUCCESS: 'GET_TASK_SUCCESS',
  GET_TASK_FAIL: 'GET_TASK_FAIL',

  ADD_TASK_REQUESTING: 'ADD_TASK_REQUESTING',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_FAIL: 'ADD_TASK_FAIL',

  EDIT_TASK_REQUESTING: 'EDIT_TASK_REQUESTING',
  EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
  EDIT_TASK_FAIL: 'EDIT_TASK_FAIL',

  DELETE_TASK_REQUESTING: 'DELETE_TASK_REQUESTING',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_FAIL: 'DELETE_TASK_FAIL',
}