export const Home = "/"
export const HomeWork1 = "/hack1"
export const HomeWork2 = "/hack2"
export const HomeWork24 = "/hack2/:index"
export const HomeWork3 = "/hack3"
export const HomeWork5 = "/hack5"
export const Final = "/todo"